repos:
  - repo: https://github.com/ambv/black
    rev: 24.3.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ["--extend-ignore=E501,E203,E741,E402"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        types: [json]
  - repo: https://github.com/Enter-tainer/typstyle
    rev: "v0.11.30"
    hooks:
      - id: typstyle
